name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pull-request:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Lint
        uses: golangci/golangci-lint-action@v3
      - name: Test
        run: go test -v ./...
